[[redirects]]
from = "/github"
to = "https://github.com/chadrt21"

[[redirects]]
from = "/GitHub"
to = "https://github.com/chadrt21"

[[redirects]]
from = "/linkedin"
to = "https://www.linkedin.com/in/chadtross/"

[[redirects]]
from = "/LinkedIn"
to = "https://www.linkedin.com/in/chadtross/"

[[redirects]]
from = "/upwork"
to = "https://www.upwork.com/freelancers/~01ecbf6e6ee2174aa6"

[[redirects]]
from = "/Upwork"
to = "https://www.upwork.com/freelancers/~01ecbf6e6ee2174aa6"

[[plugins]]
  package = "@netlify/plugin-nextjs"
